- hosts: web
  tasks:
  - name: Instal Apache
    yum:
      name: httpd
      state: latest

  - name: Make sure a service is running
    systemd:
      name: httpd
      state: started
      enabled: yes
